###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe2@example.com",
    "password": "password123"
}

###
POST http://localhost:4000/session
Content-Type: application/json

{
    "email": "john.doe2@example.com",
    "password": "password123"
}